[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } # Async runtime
axum = "0.7" # Web framework
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "chrono" ] } # Database toolkit
dotenvy = "0.15" # For loading .env files
serde = { version = "1.0", features = ["derive"] } # For JSON serialization/deserialization
chrono = { version = "0.4", features = ["serde"] } # For timestamp handling
tower-http = { version = "0.5.0", features = ["cors"] }
